### ISSUE TITLE
nonportable build scripts

### ISSUE THREAD

**Issue by electricWah** [Wodan58/Joy#2]
You mention changing the `makefile` to be more portable, but `ls -Q` is available on BSD. I'm sure there are others because I've spent all day trying to get this to compile for macos to no avail

**Comment by Wodan58** [comment]
I have added the output files of the build system to the repository and changed the makefile such that creating them is a manual procedure. Please let me know if this helps.

**Comment by Wodan58** [comment]
Hi,

Not sure whether you have received a notification from GitHub.
I have posted an update and think it solves the problem.

Kind regards,
Ruurd Wiersma

Op wo 25 okt 2023 om 07:01 schreef electricWah ***@***.***>:

**Comment by electricWah** [comment]
Sorry for not seeing this sooner. Yes, I can confirm this now builds on mac! Thank you very much!
